version: '3.3'

services:
  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    ports:
    - 9092:9092